services:
  n3uron:
    image: n3uronhub/n3uron:v1.21.7
    hostname: docker-node01
    ports:
      - 8003:8003
    volumes:
      - config:/opt/n3uron/config
      - data:/opt/n3uron/data
      - licenses:/opt/n3uron/licenses
      - log:/opt/n3uron/log
    restart: always

  timescale:
    image: timescale/timescaledb:latest-pg16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=n3uron
      - POSTGRES_DB=n3-history
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  graphql-api:
    image: hasura/graphql-engine:v2.37.0-ce
    environment:
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DATABASE_URL=postgresql://postgres:n3uron@timescale:5432/n3-history
    ports:
      - 8080:8080
    restart: always

volumes:
  config:
  data:
  licenses:
  log:
  pg_data:
